server:
  address:0.0.0.0
  port:8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/emergencydb}
    username: ${DB_USERNAME:emergencyuser}
    password: ${DB_PASSWORD:emergencypass}
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      trigger-file: reload
    livereload:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL

logging:
  level:
    org.hibernate.SQL: debug

project:
  jwt:
    signKey: ${JWT_SIGN_KEY:ZGVmYXVsdERldktleUNoYW5nZUluUHJvZHVjdGlvbjEyMzQ1}
    expirationMinutes: ${JWT_EXPIRATION_MINUTES:1440}

firebase:
  service-account-path: ${FIREBASE_SERVICE_ACCOUNT_PATH:src/main/resources/emergency-kotlin-app-firebase-adminsdk-fbsvc-6fb4dc3c22.json}

