services:
  db:
    image: postgis/postgis
    container_name: postgres-postgis-fireuser
    environment:
      POSTGRES_USER: fireuser
      POSTGRES_PASSWORD: fireuser
      POSTGRES_DB: firedb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  postgres-data:

networks:
  postgres-network:
    driver: bridge
