services:
  db:
    image: postgis/postgis:latest
    container_name: postgres-postgis-fireuser
    environment:
      POSTGRES_USER: fireuser
      POSTGRES_PASSWORD: fireuser
      POSTGRES_DB: firedb
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - postgres-network

volumes:
  postgres-data:

networks:
  postgres-network:
    driver: bridge
