services:
  db:
    image: postgis/postgis:latest
    container_name: emergencydb
    environment:
      POSTGRES_USER: emergencyuser
      POSTGRES_PASSWORD: emergencypass
      POSTGRES_DB: emergencydb
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - postgres-network

volumes:
  postgres-data:

networks:
  postgres-network:
    driver: bridge
